export const GET_EMPLOYEES_PENDING = 'GET_EMPLOYEES_PENDING';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';
export const POST_EMPLOYEES_PENDING = 'POST_EMPLOYEES_PENDING';
export const POST_EMPLOYEES_SUCCESS = 'POST_EMPLOYEES_SUCCESS';
export const POST_EMPLOYEES_ERROR = 'POST_EMPLOYEES_ERROR';
