export const GET_EMPLOYEES_PENDING = 'GET_EMPLOYEES_PENDING';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';

export const GET_EMPLOYEES_WITH_DELETED_PENDING = 'GET_EMPLOYEES_WITH_DELETED_PENDING';
export const GET_EMPLOYEES_WITH_DELETED_SUCCESS = 'GET_EMPLOYEES_WITH_DELETED_SUCCESS';
export const GET_EMPLOYEES_WITH_DELETED_ERROR = 'GET_EMPLOYEES_WITH_DELETED_ERROR';

export const GET_ONE_EMPLOYEE_PENDING = 'GET_ONE_EMPLOYEE_PENDING';
export const GET_ONE_EMPLOYEE_SUCCESS = 'GET_ONE_EMPLOYEE_SUCCESS';
export const GET_ONE_EMPLOYEE_ERROR = 'GET_ONE_EMPLOYEE_ERROR';

export const GET_EMPLOYEE_BY_FIREBASE_UID_PENDING = 'GET_EMPLOYEE_BY_FIREBASE_UID_PENDING';
export const GET_EMPLOYEE_BY_FIREBASE_UID_SUCCESS = 'GET_EMPLOYEE_BY_FIREBASE_UID_SUCCESS';
export const GET_EMPLOYEE_BY_FIREBASE_UID_ERROR = 'GET_EMPLOYEE_BY_FIREBASE_UID_ERROR';

export const POST_EMPLOYEE_PENDING = 'POST_EMPLOYEE_PENDING';
export const POST_EMPLOYEE_SUCCESS = 'POST_EMPLOYEE_SUCCESS';
export const POST_EMPLOYEE_ERROR = 'POST_EMPLOYEE_ERROR';

export const PUT_EMPLOYEE_PENDING = 'PUT_EMPLOYEE_PENDING';
export const PUT_EMPLOYEE_SUCCESS = 'PUT_EMPLOYEE_SUCCESS';
export const PUT_EMPLOYEE_ERROR = 'PUT_EMPLOYEE_ERROR';

export const DELETE_EMPLOYEE_PENDING = 'DELETE_EMPLOYEE_PENDING';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_ERROR = 'DELETE_EMPLOYEE_ERROR';

export const CLEAR_ERROR = 'CLEAR_ERROR';
