export const GET_TASKS_PENDING = 'GET_TASKS_PENDING';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR';

export const GET_ONE_TASK_PENDING = 'GET_ONE_TASK_PENDING';
export const GET_ONE_TASK_SUCCESS = 'GET_ONE_TASK_SUCCESS';
export const GET_ONE_TASK_ERROR = 'GET_ONE_TASK_ERROR';

export const POST_TASK_PENDING = 'POST_TASK_PENDING';
export const POST_TASK_SUCCESS = 'POST_TASK_SUCCESS';
export const POST_TASK_ERROR = 'POST_TASK_ERROR';

export const PUT_TASK_PENDING = 'PUT_TASK_PENDING';
export const PUT_TASK_SUCCESS = 'PUT_TASK_SUCCESS';
export const PUT_TASK_ERROR = 'PUT_TASK_ERROR';

export const DELETE_TASK_PENDING = 'DELETE_TASK_PENDING';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';
