export const GET_TASKS_PENDING = 'GET_TASKS_PENDING';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR';

export const DELETE_TASKS_PENDING = 'DELETE_TASKS_PENDING';
export const DELETE_TASKS_SUCCESS = 'DELETE_TASKS_SUCCESS';
export const DELETE_TASKS_ERROR = 'DELETE_TASKS_ERROR';

export const POST_TASKS_PENDING = 'POST_TASKS_PENDING';
export const POST_TASKS_SUCCESS = 'POST_TASKS_SUCCESS';
export const POST_TASKS_ERROR = 'POST_TASKS_ERROR';
