export const GET_TIMESHEETS_PENDING = 'GET_TIMESHEETS_PENDING';
export const GET_TIMESHEETS_SUCCESS = 'GET_TIMESHEETS_SUCCESS';
export const GET_TIMESHEETS_ERROR = 'GET_TIMESHEETS_ERROR';

export const GET_ONE_TIMESHEET_PENDING = 'GET_ONE_TIMESHEET_PENDING';
export const GET_ONE_TIMESHEET_SUCCESS = 'GET_ONE_TIMESHEET_SUCCESS';
export const GET_ONE_TIMESHEET_ERROR = 'GET_ONE_TIMESHEET_ERROR';

export const POST_TIMESHEET_PENDING = 'POST_TIMESHEET_PENDING';
export const POST_TIMESHEET_SUCCESS = 'POST_TIMESHEET_SUCCESS';
export const POST_TIMESHEET_ERROR = 'POST_TIMESHEET_ERROR';

export const PUT_TIMESHEET_PENDING = 'PUT_TIMESHEET_PENDING';
export const PUT_TIMESHEET_SUCCESS = 'PUT_TIMESHEET_SUCCESS';
export const PUT_TIMESHEET_ERROR = 'PUT_TIMESHEET_ERROR';

export const DELETE_TIMESHEET_PENDING = 'DELETE_TIMESHEET_PENDING';
export const DELETE_TIMESHEET_SUCCESS = 'DELETE_TIMESHEET_SUCCESS';
export const DELETE_TIMESHEET_ERROR = 'DELETE_TIMESHEET_ERROR';
