export const GET_SUPERADMINS_PENDING = 'GET_SUPERADMINS_PENDING';
export const GET_SUPERADMINS_SUCCESS = 'GET_SUPERADMINS_SUCCESS';
export const GET_SUPERADMINS_ERROR = 'GET_SUPERADMINS_ERROR';

export const POST_SUPERADMINS_PENDING = 'POST_TIMESHEETS_PENDING';
export const POST_SUPERADMINS_SUCCESS = 'POST_TIMESHEETS_SUCCESS';
export const POST_SUPERADMINS_ERROR = 'POST_TIMESHEETS_ERROR';
