export const GET_SUPERADMINS_PENDING = 'GET_SUPERADMINS_PENDING';
export const GET_SUPERADMINS_SUCCESS = 'GET_SUPERADMINS_SUCCESS';
export const GET_SUPERADMINS_ERROR = 'GET_SUPERADMINS_ERROR';

export const GET_ONE_SUPERADMIN_PENDING = 'GET_ONE_SUPERADMIN_PENDING';
export const GET_ONE_SUPERADMIN_SUCCESS = 'GET_ONE_SUPERADMIN_SUCCESS';
export const GET_ONE_SUPERADMIN_ERROR = 'GET_ONE_SUPERADMIN_ERROR';

export const GET_SUPER_ADMIN_BY_FIREBASE_UID_PENDING = 'GET_SUPER_ADMIN_BY_FIREBASE_UID_PENDING';
export const GET_SUPER_ADMIN_BY_FIREBASE_UID_SUCCESS = 'GET_SUPER_ADMIN_BY_FIREBASE_UID_SUCCESS';
export const GET_SUPER_ADMIN_BY_FIREBASE_UID_ERROR = 'GET_SUPER_ADMIN_BY_FIREBASE_UID_ERROR';

export const POST_SUPERADMIN_PENDING = 'POST_SUPERADMIN_PENDING';
export const POST_SUPERADMIN_SUCCESS = 'POST_SUPERADMIN_SUCCESS';
export const POST_SUPERADMIN_ERROR = 'POST_SUPERADMIN_ERROR';

export const PUT_SUPERADMIN_PENDING = 'PUT_SUPERADMIN_PENDING';
export const PUT_SUPERADMIN_SUCCESS = 'PUT_SUPERADMIN_SUCCESS';
export const PUT_SUPERADMIN_ERROR = 'PUT_SUPERADMIN_ERROR';

export const DELETE_SUPERADMIN_PENDING = 'DELETE_SUPERADMIN_PENDING';
export const DELETE_SUPERADMIN_SUCCESS = 'DELETE_SUPERADMIN_SUCCESS';
export const DELETE_SUPERADMIN_ERROR = 'DELETE_SUPERADMIN_ERROR';
