export const GET_PROJECTS_PENDING = 'GET_PROJECTS_PENDING';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';
export const POST_PROJECT_PENDING = 'POST_PROJECT_PENDING';
export const POST_PROJECT_SUCCESS = 'POST_PROJECT_SUCCESS';
export const POST_PROJECT_ERROR = 'POST_PROJECT_ERROR';
