export const GET_ADMINS_PENDING = 'GET_ADMINS_PENDING';
export const GET_ADMINS_SUCCESS = 'GET_ADMINS_SUCCESS';
export const GET_ADMINS_ERROR = 'GET_ADMINS_ERROR';
export const POST_ADMINS_PENDING = 'POST_ADMINS_PENDING';
export const POST_ADMINS_SUCCESS = 'POST_ADMINS_SUCCESS';
export const POST_ADMINS_ERROR = 'POST_ADMINS_ERROR';
